{% set version = "1.2.0" %}

package:
  name: numpy-allocator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy-allocator/numpy-allocator-{{ version }}.tar.gz
  sha256: 5126bc811253c64b16d5a7cd2308ffc5079fb427ceaef087696b83e669f0dc9a

build:
  script:
    - rm pyproject.toml   # [unix]
    - del pyproject.toml  # [win]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.22                             # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    # must build with at least 1.22 since that is when the API was introduced
    - numpy 1.22  # [py<311]
    - numpy       # [py>=311]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - numpy_allocator
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/inaccel/numpy-allocator
  summary: Customize Memory Allocators in NumPy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
    - eliaskoromilas
